server:

  port: 8999

 

eureka:

  instance:

    hostname: localhost  

 

spring:

  application:

    name: Gateway_API_Service

    

  cloud:

    gateway:

      routes:

 

        - id: Product-Service

          uri: lb://Product-Service

          predicates:

          - Path=/pps/**